language: node_js
node_js:
  - 0.8
  - 0.9
before_install:
# Ruby
- sudo apt-get -y install git-core curl
- curl https://raw.github.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
- rbenv install 1.9.3-p194
- rbenv global 1.9.3-p194
- rbenv update
- rbenv bootstrap-ubuntu-12-04
- rbenv bootstrap
# Python
# - sudo add-apt-repository ppa:fkrull/deadsnakes
# - sudo apt-get update
# - sudo apt-get install python2.7
