language: node_js
node_js:
  - 0.8
  - 0.9
before_install:
# Ruby
- sudo gem install bundler
# Python
# - sudo add-apt-repository ppa:fkrull/deadsnakes
# - sudo apt-get update
# - sudo apt-get install python2.7
